### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by mbartok** [bicpi/HtmlConverterBundle#1]
It would by nice to have Symfony 3 compatibility. HtmlConverter is requiring symfony/process version 2.*.

**Comment by bicpi** [comment]
@mbartok Thanks for your interest in this bundle.

I've just released new major versions for `bicpi/HtmlConverter` (2.0.0) and `bicpi/HtmlConverterBundle` (2.0.0) with Symfony 3 support (PHP 5.3/5.4 and Symfony < 2.7 support was dropped).
